global:
  scrape_interval: 15s # default = 60s
  evaluation_interval: 30s # default = 60s
  # scrape_timeout = default (10s)

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'synthetic-monitoring'
    static_configs:
      - targets: ['synthetic-monitoring:9091']
    scrape_interval: 60s

  - job_name: 'blackbox-website-monitoring'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://cmucourses.com
        labels:
          instance: 'cmucourses'

      - targets:
          - https://cmueats.com
        labels:
          instance: 'cmueats'

      - targets:
          - https://maps.scottylabs.org
        labels:
          instance: 'cmumaps'

      - targets:
          - https://lostandfound.andrew.cmu.edu
        labels:
          instance: 'lostandfound'

      - targets:
          - https://www.scottylabs.org
        labels:
          instance: 'sl-main-site'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      # saves full URL to label 'url' for logs
      - source_labels: [__address__]
        target_label: url

      - target_label: __address__
        replacement: blackbox-exporter:9115
